nmHoistingLimits: none

nmSelfReferences: true

nodeLinker: node-modules

npmScopes:
  logi-x:
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"
