nmHoistingLimits: none

nmSelfReferences: true

nodeLinker: node-modules

npmScopes:
  logi-x:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: ${YARN_NPM_AUTH_TOKEN}
